### PR TITLE
Forward all directiveResolver args. Closes #108

### LINKED ISSUE #108: Forward all directiveResolver args
Currently the directive resolvers `auth`, `hasRole` etc only forwards graphql params `root`, `args`, `context`, `info`.

This is generally sufficient but is an issue when using with prisma/nexus and other plugins that many need to add more arguments.

In my case, graphql nexus adds a fourth argument that allows [custom resolvers](https://github.com/graphql-nexus/nexus-plugin-prisma/pull/674#issuecomment-639584966) to intercept requests. 

An example for a directiveResolver to  solve this problem could look like this
```javascript
exports.auth = (next) => () => {
    if (!context[KeycloakContext_1.CONTEXT_KEY] || !context[KeycloakContext_1.CONTEXT_KEY].isAuthenticated()) {
        const error = new Error(`User not Authenticated`);
        error.code = "UNAUTHENTICATED";
        throw error;
    }
    return next.apply( this, arguments ); 
};
```

### PR DESCRIPTION
**Pull request by wtrocki**
Manual CI/CD testing PR on Jenkins

### CODE REVIEW

**Comment by wtrocki** [comment]
Passed! Thanks @augustusnaz

**Comment by wtrocki** [comment]
Manual prepublish checks passed. Released. 

We need to automate all of those as it takes so much time.

**Comment by augustusnaz** [comment]
Hi @wtrocki the release has not reflected on github yet. Not sure why 😞. npm install still has 0.6.0 code

**Comment by wtrocki** [comment]
https://www.npmjs.com/package/keycloak-connect-graphql

**Comment by wtrocki** [comment]
It has 0.6.1

**Comment by augustusnaz** [comment]
Sorry for the late reply man. 
Yes, npm has 0.6.1 but the installed dist is still 0.6.0 builds 😞

**Comment by wtrocki** [comment]
Ok.. I will rebuild it for you again..
Sorry for problem

**Comment by wtrocki** [comment]
Released! See keycloak-connect-graphql@0.6.2

**Comment by wtrocki** [comment]
keycloak-connect-graphql@0.6.3

Another release. Previous was wrong.

We will introduce testing using released version (currently we build one and release failed due to invalid config in the npm,tsconfig.

**Pull request merged**
