### PR TITLE
Adding example documentation for using apollo-server-express v3 transformers

### PR DESCRIPTION
**Pull request by BigBallard**
Attempted to add the transformers to the this lib but for obvious reasons of using asev3 in your project, there are v2 dependencies in this lib cant be resolved in your project. So I just added documentation for implementing the transformers yourself borrowing this libs logic. Hope it helps.

### CODE REVIEW

**Comment by wtrocki** [comment]
I do not think that anyone uses Apollo 2 anymore. I think we can kill completely support for Apollo 2 and assume that everything should work on with 3.

**Comment by wtrocki** [comment]
As well. I'm pretty much still have projects/users using this lib with Apollo 3 by building their schema using graphql-tools. 
I would rather prefer graphql-tools rather than using some `semi open source` features of Apollo platform. This way you could use library with graphql-express or apollo-server without difference

**Comment by DallasP9124** [comment]
Ya I would agree with that. Besides, if anyone does use Apollo 2 this version is still available, we would just up the major version. Should we merge these docs for the time being and work on migrating to exclusive Apollo 3, or what would be that path forward, I would like to help 👍

**Comment by wtrocki** [comment]
Thank you so much! It will be hard for me to run the code in the docs but as form of encouragement I will merge that back and see if we can pull all of that into current example application instead later phase.

**Pull request merged**
